### PR TITLE
Bug Fix for When Mash Output is Empty

### PR DESCRIPTION
**Pull request by emarinier**
This pull request addresses #3.

I've tried to keep the programming style mostly similar. I handle empty files by returning a `None` dataframe when the output is empty and then add logic to handle when dataframes are `None`.

### CODE REVIEW

**Comment by peterk87** [comment]
Looks good to me!

If it's not too much trouble, the tiny FASTQ file could be added as test data and a test case could be added to [tests/test_contains.py](https://github.com/phac-nml/refseq_masher/blob/master/tests/test_contains.py). Maybe something like this


```python
def test_tiny_fastq(runner):
    fastq = 'tests/data/tiny.fastq'
    result = runner.invoke(cli.contains, ['-p', '4',
                                          fastq])

    assert result.exit_code == 0, 'Exit code should be 0'
    assert 'There were no matches found.' in result.error, 'Should be a log message indicating no matches were found.'
    assert len(result.output) == 0, 'No output results on empty data' # if that makes sense
```

I haven't tested the above.

**Comment by emarinier** [comment]
I'm having trouble writing a test to check the logs for the `There were no matches found.` message. Sticking with the style of program, such messages tend to use `logging.info()`.

When I enable --verbose and run the program, the output doesn't change and I don't see a logfile is created:

```
> refseq_masher --verbose contains -p 4 tests/data/small.fastq

Loading RefSeqSketches.msh...
   4669418 distinct hashes.
Streaming from tests/data/small.fastq...
   Estimated distinct k-mers in pool: 86
Summing shared...
Computing coverage medians...
Writing output...
```

I suspect this may be in part because the click function that enables verbose output is passing the wrong parameters:

```
def cli(verbose):
    """Find the closest matching NCBI RefSeq genomes or the genomes contained in your contigs or reads.
    """
    lvl = init_console_logger(verbose)
    logging.debug('Initialized logging with %s level', lvl)
```

As far as I'm aware, `verbose` is effectively a boolean. The value is either 0 or 1 depending on whether `--verbose` has been flagged. The function that initializes the console logger is only ever passed 0 or 1, which I believe corresponds to ERROR and WARN, respectively, but never INFO or DEBUG:

```
def init_console_logger(logging_verbosity=3):
    logging_levels = [logging.ERROR, logging.WARN, logging.INFO, logging.DEBUG]
    if logging_verbosity > (len(logging_levels) - 1):
        logging_verbosity = 3
    lvl = logging_levels[logging_verbosity]

    logging.basicConfig(format=LOG_FORMAT, level=lvl)
    return lvl
```

I can try to make changes to correct the logging functionality, but it might be beyond the scope of this bugfix. I've written the test as suggested, simply to check that there is no error thrown, and that the output is empty:

```
def test_small_fastq(runner):
    fastq = 'tests/data/small.fastq'
    result = runner.invoke(cli.contains, ['-p', '4', fastq])

    assert result.exit_code == 0, 'Exit code should be 0'
    assert len(result.stdout) == 0, 'No output results on empty data'
```

**Comment by emarinier** [comment]
Sorry, wrote a comment and realized I was wrong about logging. I'm going to try updating the tests.

**Comment by emarinier** [comment]
Okay, what an adventure, but I found out how to check logs in testing:

```
    def test_small_fastq(self):
        fastq = 'tests/data/small.fastq'
        runner = CliRunner()

        with self.assertLogs(level='INFO') as cm:
            result = runner.invoke(cli.contains, ['-p', '4', fastq])
            assert "There were no matches found." in " ".join(cm.output)

        assert result.exit_code == 0, 'Exit code should be 0'
        assert len(result.stdout) == 0, 'No output results on empty data'
```

**Review by ericenns — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
